### ISSUE TITLE
Test for multiple forward-slashes seems not to work correctly

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/ocsp_monitor#4]
I identified a possible error in the test of OCSP responders for multiple forward-slashes. When I do manually a

```
curl --verbose --url http://ocsp.siemens.com/MEwwSjBEMEIwPDAJBgUrDgMCGgUABBQZi38wFNaJswehTpPKVshbSQ+GwAQUkssAaDtwlx2UmxiRvoReHJS6sagCAwP%2F%2FKACMACiAjAA`
```

I get as result:

```
*   Trying 129.103.196.20...
* TCP_NODELAY set
* Connected to ocsp.siemens.com (129.103.196.20) port 80 (#0)
> GET /MEwwSjBEMEIwPDAJBgUrDgMCGgUABBQZi38wFNaJswehTpPKVshbSQ+GwAQUkssAaDtwlx2UmxiRvoReHJS6sagCAwP%2F%2FKACMACiAjAA HTTP/1.1
> Host: ocsp.siemens.com
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 400
< Connection: close
< Date: Wed, 05 Jan 2022 10:28:52 GMT
< Content-length: 0
<
* Closing connection 0
```

But according to [crt.sh/ocsp-responders](https://crt.sh/ocsp-responders?trustedExclude=&trustedBy=&trustedFor=&dir=v&sort=2&url=%25ocsp.siemens.com&get=&post=&getrandomserial=&postrandomserial=&getforwardslashes=) this OCSP responder is answering 'try later': 
![image](https://user-images.githubusercontent.com/1633499/148203819-d767d90b-bc16-4d88-902e-5adb9662e80b.png)

**Comment by RufusJWB** [comment]
I believe the problem comes, because you are doing an

`url.QueryEscape(base64.StdEncoding.EncodeToString(ocsp_req_bytes))`

https://github.com/crtsh/ocsp_monitor/blob/903a5b54be6c09d8842a37a263a456af036b8035/ocsp_monitor.go#L232

**Comment by RufusJWB** [comment]
@robstradling did you have a chance to have a look into this issue?

**Comment by robstradling** [comment]
@RufusJWB Sorry, not yet.

**Comment by robstradling** [comment]
@RufusJWB Line 232 is doing exactly the right thing.  Without the "base64.StdEncoding.EncodeToString" call, the GET URL would contain binary data instead of base64-encoded data; and without the url.QueryEscape call, the GET URL would contain "/" instead of "%2F".

This is the URL that crt.sh is actually checking:
`http://ocsp.siemens.com/MEQwQjBAMD4wPDAJBgUrDgMCGgUABBQAAAAAAAAAAAAAAAAAAAAAAAAAAAQUAAAAAAAAAAAAAAAAAAAAAAAAAAACAwP%2F%2FA%3D%3D`
My intention was that this would be identical to Corey's example URL (see https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/cMegyySSqhM/m/G7s5tFR4BAAJ), except that the Issuer Name Hash and Issuer Key Hash values are both zeroized.  On closer inspection I just noticed that Corey's example includes empty SEQUENCEs for the optional "singleRequestExtensions" and "requestExtensions" (whereas crt.sh omits these), but this difference seems to be immaterial.

It looks like the actual problem is that you didn't URL-encode the "+" in your manual cURL request.  It needs to be "%2B" so that it doesn't get URL-decoded to a SPACE character by ocsp.siemens.com.

**Comment by robstradling** [comment]
@RufusJWB Oh, I see you and Corey discussed the issue of whether or not "+" characters need to be encoded to "%2B" a few weeks ago:
https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/cMegyySSqhM/m/OeDkXmplAwAJ
https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/cMegyySSqhM/m/zcJwbdNnAwAJ

Anyway, whether or not Corey's argument is correct, ISTM that there's no problem with what crt.sh is doing.

**Comment by robstradling** [comment]
> It looks like the actual problem is that you didn't URL-encode the "+" in your manual cURL request. It needs to be "%2B" so that it doesn't get URL-decoded to a SPACE character by ocsp.siemens.com.

Ignore that last bit.  After doing a bit more reading I now understand that the encoding of SPACEs to "+"s (and unencoding "+"s to SPACEs) only occurs with HTML form encoding (i.e., Content-Type: application/x-www-form-urlencoded), so it's not relevant to OCSP.

I think Corey's answer (https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/cMegyySSqhM/m/zcJwbdNnAwAJ) is correct.

**Comment by RufusJWB** [comment]
> I think Corey's answer (https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/cMegyySSqhM/m/zcJwbdNnAwAJ) is correct.

I think so too :-) And that is the core of the problem here: In Coreys original example payload (`MEwwSjBEMEIwPDAJBgUrDgMCGgUABBQZi38wFNaJswehTpPKVshbSQ+GwAQUkssAaDtwlx2UmxiRvoReHJS6sagCAwP%2F%2FKACMACiAjAA`) there is a plus sign included and in the one crt.sh is using (`MEQwQjBAMD4wPDAJBgUrDgMCGgUABBQAAAAAAAAAAAAAAAAAAAAAAAAAAAQUAAAAAAAAAAAAAAAAAAAAAAAAAAACAwP%2F%2FA%3D%3D`) there is **no** plus sign included.

![image](https://user-images.githubusercontent.com/1633499/155020844-07e51c24-08bd-4a43-a834-6dac9c92d1c3.png)

If you would have a (valid) plus sign in your example payload much more OCSP responders would fail.

**Comment by robstradling** [comment]
I'm going to add a separate "unencoded +" test.  :-)
